language:python
python:
	-"2.7"
install:
	-"pip install -r requirements.txt"
	-"pip install coveralls"
script: 
	coverage run --source=moscowdjango,meetup manage.py test
#whitelist
brances:
	only:
		- master
brances:
	except:
		-develop
		-feature
before_script:
	-./lint.sh
after_success:
	coveralls

